# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e147724db5a69c4892b3ca90b7dd58310ecffd5d416a05b2a7597bdd75725f927b0ae124795c94776278db60e8e208deefdd41b30723cb775ef91eee71651ba

test:
  secret_key_base: aaaec3bb7be1b8416c665df7211eb98c6abb385dc16619a7854e3dce7d0da389c9177dcab5374e8d4ba3defe893db5b85172cb7b7019e0d2dea572911289175b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
